### ISSUE TITLE
Distanz Problem

### ISSUE THREAD

**Issue by fohnbit** [fohnbit/radarCat#2]
Hello @erikmansson 

I modified for my radar system your example codes. I want to measure the speed and send then a picture. This is working so far, but when I increase the Distance to 1.50m, then I get no data:

https://github.com/fohnbit/radarCat/blob/86dbd2d08a302877486148aed30ccac9e0fbe797/examples/processing/sparse_speed.py#L81-L91

I guess this lines has to optimize?
For sure to set the range to 1.50 and 1.90 ... but then I get no speed results

Thank you!

**Comment by erikmansson** [comment]
What happens here is that you're requesting data that doesn't fit into the buffer - so it fails. This is very hard to figure out on your own here. We're working on making this more clear.

The buffer usage is the number of depths times the number of subsweeps. It may not exceed 2048 data points. By default, `config.number_of_subsweeps = NUM_FFT_BINS = 512`, which allows for measuring 4 depths. The default range setting of `[0.30, 0.48] ` and a stepsize of 3 will result in 2 depths - 30 and 48 cm. Setting `[0.30, 0.66]` and stepsize 3 results in 3 depths - 30, 48 and 66 cm.

To solve this I would start by dropping `NUM_FFT_BINS` to 256 or even possibly 128 if that's not enough.

**Comment by fohnbit** [comment]
Hello Erik,

I changed distance to 2.00, 2.20 and the NUM_FFT_BINS to 256 and 128 ... but never get a speed. When I set the range to 0.30, 0.66 its seems working.

The distance seems not correct, but this I investigate later.

I updated my repo according your infos.
https://github.com/fohnbit/radarCat/blob/9d0aa8a7773fc7daaa814748f84ebca9d6cdca44/examples/processing/sparse_speed.py#L85

Maybe you could test why I get no speed measuring?

Thank you

**Comment by erikmansson** [comment]
That is so strange. You should get the actual range points at 1.98 and 2.16 m, which should be completely fine. I noticed now that this is exactly what you're getting in the other issue.

Since this is the same issue as the other one in our repo, I'll continue helping you there.
